# Generated by Django 3.2.6 on 2021-08-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imobiliarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Endereco', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='Caracteristica',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='Finalidade',
            field=models.CharField(blank=True, choices=[('Residencial', 'Residencial'), ('Escritorio', 'Escritorio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='Status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='Tipo',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa')], max_length=15),
        ),
    ]
