# Generated by Django 3.2.6 on 2021-08-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210805_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imobiliarias',
            new_name='Imobiliaria',
        ),
    ]
